version: '3'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'devbills'
      MONGO_INITDB_ROOT_PASSWORD: 'pass123'
    ports:
      - '27017:27017'
    volumes:
      - ./mongod.conf:/etc/mongo/mongod.conf   # Monta o arquivo de configuração
    command: mongod --config /etc/mongo/mongod.conf  # Usar arquivo de configuração
    networks:
      - local

  app:
    depends_on:
      - mongo
    container_name: devbills-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
    ports:
      - '3333:3333'
    networks:
      - local
    env_file:
      - .env
    command: npm run dev  # Comando para iniciar a aplicação Node.js

networks:
  local:
    driver: bridge
